# Generated by Django 4.2.30 on 2026-06-07 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipai_agent_id', models.IntegerField(blank=True, null=True, verbose_name='FIPAI Agent ID')),
                ('agent_name', models.CharField(max_length=200, verbose_name='Agent名称')),
                ('agent_type', models.CharField(choices=[('community', '社群助手'), ('matching', '匹配助手'), ('publish', '发布助手'), ('supply_demand', '供需助手'), ('network', '人脉助手'), ('event', '活动助手'), ('custom', '自定义')], default='custom', max_length=50, verbose_name='Agent类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('capabilities', models.JSONField(default=list, verbose_name='能力列表')),
                ('config', models.JSONField(default=dict, verbose_name='业务配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent业务配置',
                'db_table': 'console_agent_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', '管理员'), ('superuser', '超级用户'), ('regular', '普通用户')], default='regular', max_length=20, verbose_name='用户类型')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='公司')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('plan', models.CharField(choices=[('free', '免费版'), ('pro', '专业版'), ('enterprise', '企业版')], default='free', max_length=20, verbose_name='套餐')),
                ('max_agents', models.IntegerField(default=3, verbose_name='最大Agent数')),
                ('token_quota', models.BigIntegerField(default=100000, verbose_name='Token配额')),
                ('token_used', models.BigIntegerField(default=0, verbose_name='已用Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='console_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'db_table': 'console_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.BigIntegerField(default=0, verbose_name='Token消耗')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='费用')),
                ('request_count', models.IntegerField(default=0, verbose_name='请求次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='console.agentconfig', verbose_name='Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用量记录',
                'db_table': 'console_usage_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('platform', models.CharField(choices=[('wechat', '微信'), ('weibo', '微博'), ('dingtalk', '钉钉'), ('feishu', '飞书'), ('custom', '自定义')], default='custom', max_length=50, verbose_name='发布平台')),
                ('status', models.CharField(choices=[('pending', '待发布'), ('published', '已发布'), ('failed', '发布失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.agentconfig', verbose_name='Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '发布任务',
                'db_table': 'console_publish_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_id', models.CharField(blank=True, max_length=100, verbose_name='需求ID')),
                ('supply_id', models.CharField(blank=True, max_length=100, verbose_name='供给ID')),
                ('match_score', models.FloatField(default=0, verbose_name='匹配分数')),
                ('status', models.CharField(choices=[('pending', '待匹配'), ('matched', '已匹配'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.agentconfig', verbose_name='Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '匹配记录',
                'db_table': 'console_matching_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
