# Generated by Django 5.2.13 on 2026-05-04 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_url', models.URLField(blank=True, default='', max_length=512)),
                ('activity_type', models.SmallIntegerField(choices=[(1, '沙龙'), (2, '路演'), (3, '培训班'), (4, '社交聚会'), (5, '线上讲座')])),
                ('host_school', models.CharField(blank=True, default='', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=256)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('current_attendees', models.IntegerField(default=0)),
                ('enrollment_mode', models.SmallIntegerField(choices=[(1, '免费'), (2, '付费'), (3, '审核')], default=1)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tags', models.JSONField(default=list)),
                ('status', models.SmallIntegerField(choices=[(1, '报名中'), (2, '进行中'), (3, '已结束'), (4, '已取消')], default=1)),
                ('ai_match_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_activities', to='profiles.profile')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEnrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrollment_status', models.SmallIntegerField(choices=[(1, '已报名'), (2, '已确认'), (3, '已取消'), (4, '已签到')], default=1)),
                ('ai_recommended', models.BooleanField(default=False)),
                ('ai_match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='activities.activity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='profiles.profile')),
            ],
            options={
                'db_table': 'activity_enrollments',
                'unique_together': {('activity', 'profile')},
            },
        ),
    ]
