# Generated by Django 4.2.30 on 2026-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='audit_comment',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='activity',
            name='audit_status',
            field=models.SmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核拒绝')], default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='audit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
