# Generated by Django 4.2.30 on 2026-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', '管理员'), ('superuser', '超级用户'), ('regular', '普通用户')], default='regular', max_length=20, verbose_name='用户类型'),
        ),
    ]
