# Generated by Django 5.2.13 on 2026-05-04 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conn_type', models.SmallIntegerField(choices=[(1, '好友'), (2, '粉丝'), (3, '校友'), (4, '活动认识'), (5, '供需认识')])),
                ('relation_strength', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('last_interact_at', models.DateTimeField(blank=True, null=True)),
                ('interact_count', models.IntegerField(default=0)),
                ('is_mutual', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(1, '有效'), (2, '已删除')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connections',
                'ordering': ['-relation_strength'],
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trigger_event', models.SmallIntegerField(choices=[(1, '刚匹配'), (2, '活动结束'), (3, '社群互动'), (4, '自定义')])),
                ('ai_script', models.TextField(blank=True, default='')),
                ('followup_type', models.SmallIntegerField(choices=[(1, 'AI建议'), (2, '已发送'), (3, '已回复'), (4, '已添加微信')], default=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.SmallIntegerField(blank=True, choices=[(1, 'positive'), (2, 'neutral'), (3, 'negative')], null=True)),
                ('result_text', models.TextField(blank=True, default='')),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, '已计划'), (2, '已发送'), (3, '已完成')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups_from', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups_to', to='profiles.profile')),
            ],
            options={
                'db_table': 'followups',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('supply_type', models.SmallIntegerField(choices=[(1, '供给'), (2, '需求')])),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(default=list)),
                ('match_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(1, '有效'), (2, '已下架'), (3, '已成交')], default=1)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='profiles.profile')),
            ],
            options={
                'db_table': 'supplies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('embedding', models.JSONField(default=list)),
                ('model_name', models.CharField(default='text-embedding-3-small', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='supplies.supply')),
            ],
            options={
                'db_table': 'supply_embeddings',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('match_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('ai_reason', models.TextField(blank=True, default='')),
                ('match_type', models.SmallIntegerField(choices=[(1, '供需匹配'), (2, '人脉推荐'), (3, '活动推荐')])),
                ('status', models.SmallIntegerField(choices=[(1, '待处理'), (2, '已联系'), (3, '已成交'), (4, '已忽略')], default=1)),
                ('push_status', models.SmallIntegerField(choices=[(0, '未推送'), (1, '已推送'), (2, '已点击'), (3, '已反馈')], default=0)),
                ('feedback_score', models.SmallIntegerField(blank=True, choices=[(1, '准确'), (2, '一般'), (3, '不匹配')], null=True)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to='profiles.profile')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='supplies.supply')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-match_score'],
                'unique_together': {('supply', 'target_profile', 'match_type')},
            },
        ),
    ]
