# Generated by Django 4.2.30 on 2026-06-02 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar_privatemessage'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='audit_status',
            field=models.SmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核拒绝')], default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='audit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.SmallIntegerField(choices=[(1, '待接受'), (2, '已接受'), (3, '已拒绝'), (4, '已过期')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='profiles.profile')),
            ],
            options={
                'db_table': 'friend_requests',
                'ordering': ['-created_at'],
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
    ]
