# Generated by Django 4.2.30 on 2026-05-14 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_friend_request_and_private_message'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.SmallIntegerField(choices=[(1, '待接受'), (2, '已接受'), (3, '已拒绝'), (4, '已过期')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to='profiles.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='profiles.profile')),
            ],
            options={
                'db_table': 'friend_requests',
                'ordering': ['-created_at'],
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
    ]
