# Generated by Django 4.2.30 on 2026-05-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_add_friend_request_and_private_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
