# Generated by Django 4.2.30 on 2026-06-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supply_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
