# Generated by Django 4.2.30 on 2026-06-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_supply_audit_status_supply_audit_time_and_more'),
        ('supplies', '0004_supply_images'),
    ]

    operations = [
    ]
