# Generated by Django 5.2.13 on 2026-05-04 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('channel', models.SmallIntegerField(choices=[(1, 'AI助手Q'), (2, 'AI发布引导S'), (3, 'AI匹配反馈K')])),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('context_summary', models.TextField(blank=True, default='')),
                ('message_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='users.user')),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.SmallIntegerField(choices=[(1, 'user'), (2, 'assistant'), (3, 'system')])),
                ('content', models.TextField()),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
