# Generated by Django 5.2.13 on 2026-05-04 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('l1_category', models.CharField(choices=[('供给资源', '供给资源'), ('需求帮助', '需求帮助'), ('行业经验', '行业经验'), ('投资意向', '投资意向'), ('社交兴趣', '社交兴趣')], max_length=32)),
                ('l2_group', models.CharField(blank=True, default='', max_length=32)),
                ('l3_item', models.CharField(blank=True, default='', max_length=64)),
                ('l4_attr', models.CharField(blank=True, default='', max_length=64)),
                ('l5_detail', models.CharField(blank=True, default='', max_length=64)),
                ('tag_type', models.SmallIntegerField(choices=[(1, '供给'), (2, '需求'), (3, '通用')], default=3)),
                ('is_recommend', models.BooleanField(default=False)),
                ('hot_score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-hot_score'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('real_name', models.CharField(max_length=64)),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.CharField(blank=True, default='', max_length=128)),
                ('industry', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('bio', models.TextField(blank=True, default='')),
                ('education_year', models.CharField(blank=True, default='', max_length=10)),
                ('education_major', models.CharField(blank=True, default='', max_length=128)),
                ('education_school', models.CharField(blank=True, default='', max_length=128)),
                ('cert_level', models.SmallIntegerField(choices=[(0, '未认证'), (1, '手机认证'), (2, '校友认证'), (3, '深度认证')], default=0)),
                ('cert_status', models.SmallIntegerField(default=0)),
                ('cert_document_url', models.URLField(blank=True, default='', max_length=512)),
                ('conn_count', models.IntegerField(default=0)),
                ('active_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('embedding', models.JSONField(default=list)),
                ('model_name', models.CharField(default='text-embedding-3-small', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='profiles.profile')),
            ],
            options={
                'db_table': 'profile_embeddings',
            },
        ),
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag_type', models.SmallIntegerField(choices=[(1, '供给标签'), (2, '需求标签')])),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('is_ai_ext', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='profiles.profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tag')),
            ],
            options={
                'db_table': 'profile_tags',
                'unique_together': {('profile', 'tag')},
            },
        ),
    ]
