# Generated by Django 4.2.30 on 2026-05-14 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cert_type', models.SmallIntegerField(choices=[(1, '身份认证'), (2, '职业认证'), (3, '学历认证')])),
                ('status', models.SmallIntegerField(choices=[(0, '草稿'), (1, '审核中'), (2, '已通过'), (3, '未通过')], default=0)),
                ('real_name', models.CharField(max_length=64)),
                ('id_number', models.CharField(blank=True, default='', max_length=32)),
                ('organization', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.CharField(blank=True, default='', max_length=128)),
                ('credential_number', models.CharField(blank=True, default='', max_length=64)),
                ('front_image', models.URLField(blank=True, default='', max_length=512)),
                ('back_image', models.URLField(blank=True, default='', max_length=512)),
                ('credential_image', models.URLField(blank=True, default='', max_length=512)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.profile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
