# Generated by Django 4.2.30 on 2026-06-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='profiles.profile')),
            ],
            options={
                'db_table': 'contact_tags',
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContactTagRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='profiles.profile')),
                ('contact_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='profiles.contacttag')),
            ],
            options={
                'db_table': 'contact_tag_relations',
                'unique_together': {('contact_tag', 'contact_profile')},
            },
        ),
    ]
