# Generated by Django 4.2.30 on 2026-05-19 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_friend_request_and_private_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.SmallIntegerField(choices=[(1, '新私信'), (2, '新匹配'), (3, '好友请求'), (4, '帖子回复'), (5, '活动提醒'), (6, '系统通知')])),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, default='')),
                ('related_url', models.CharField(blank=True, default='', max_length=256)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profiles.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='profiles.profile')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
