# Generated by Django 4.2.30 on 2026-06-03 22:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_add_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('company', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.CharField(blank=True, default='', max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('wechat', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.CharField(blank=True, default='', max_length=128)),
                ('bio', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('visibility', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='profiles.profile')),
            ],
            options={
                'db_table': 'cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
