# Generated by Django 4.2.30 on 2026-06-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar_privatemessage'),
        ('profiles', '0005_add_card_model'),
    ]

    operations = [
    ]
