# Generated by Django 5.2.13 on 2026-05-04 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('wx_openid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('wx_unionid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=64)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=512)),
                ('status', models.SmallIntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
