# Generated by Django 4.2.30 on 2026-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='手机已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_code_fail_count',
            field=models.IntegerField(default=0, verbose_name='验证码失败次数'),
        ),
    ]
