# Generated by Django 4.2.30 on 2026-05-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
