# Generated by Django 5.2.13 on 2026-06-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_phone_verified_user_real_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
