# Generated by Django 4.2.30 on 2026-06-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email'),
        ('users', '0004_remove_user_is_staff_remove_user_is_superuser_and_more'),
    ]

    operations = [
    ]
