# Generated by Django 5.2.13 on 2026-05-04 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('community_type', models.SmallIntegerField(choices=[(1, '行业社群'), (2, '地域社群'), (3, '校友群'), (4, '兴趣社群')])),
                ('school', models.CharField(blank=True, default='', max_length=128)),
                ('cover_url', models.URLField(blank=True, default='', max_length=512)),
                ('member_count', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(1, '公开'), (2, '私密'), (3, '已解散')], default=1)),
                ('qr_code_url', models.URLField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_communities', to='profiles.profile')),
            ],
            options={
                'db_table': 'communities',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('msg_type', models.SmallIntegerField(choices=[(1, '文本'), (2, '图片'), (3, '链接'), (4, '小程序')], default=1)),
                ('is_pinned', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(default=0)),
                ('ai_signal_type', models.SmallIntegerField(blank=True, choices=[(1, '供需信号'), (2, '问答信号'), (3, '合作意向'), (4, '资源推介')], null=True)),
                ('ai_signal_extracted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communities.community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='profiles.profile')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.SmallIntegerField(choices=[(1, '普通成员'), (2, '管理员'), (3, '群主')], default=1)),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '已退出'), (3, '已移除')], default=1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to='profiles.profile')),
            ],
            options={
                'db_table': 'community_members',
                'unique_together': {('community', 'profile')},
            },
        ),
    ]
